"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from typing import Optional


@dataclasses.dataclass
class GetSubtreeRequest:
    rocket_node_path: str = dataclasses.field(metadata={'path_param': { 'field_name': 'rocketNodePath', 'style': 'simple', 'explode': False }})
    r"""Target node."""
    



@dataclasses.dataclass
class GetSubtreeResponseBody:
    r"""Return target subtree."""
    



@dataclasses.dataclass
class GetSubtreeResponse:
    content_type: str = dataclasses.field()
    r"""HTTP response content type for this operation"""
    status_code: int = dataclasses.field()
    r"""HTTP response status code for this operation"""
    raw_response: requests_http.Response = dataclasses.field()
    r"""Raw HTTP response; suitable for custom response parsing"""
    object: Optional[GetSubtreeResponseBody] = dataclasses.field(default=None)
    r"""Subtree retrieved successfully."""
    

